version: 43.0.9
pageUuid: 494c65ce-4649-11eb-ad07-9b80cb786a35
appTemplate:
  urlFragmentDefinitions: []
  appStyles: ''
  appThemeId: null
  preloadedAppJavaScript: null
  pageLoadValueOverrides: []
  customDocumentTitle: ''
  isGlobalWidget: false
  isFetching: true
  instrumentationEnabled: false
  customDocumentTitleEnabled: false
  preloadedAppJSLinks:
    array: []
  version: 2.66.88
  responsiveLayoutDisabled: false
  createdAt: null
  loadingIndicatorsDisabled: false
